# Supabase Configuration File

project_id = "tcwmbwkvflnranchrhyr"

[api]
enabled = true
port = 54321
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600

[functions.render-video]
verify_jwt = false

[functions.check-render-status]
verify_jwt = false
